# The yaml file is a temporary example, of the configuration information read by the purger

# Age of data to be retained, all data that is older than this value will be removed by the purge process.
age: 5 minutes
# A boolean switch that can be used to disable the purging of data. This is used if the process should be stopped from running.
enabled: True
# time until next run (assume in seconds)
wait: 1