# The yaml file is a temporary example, of the configuration information read by the purger

# Age of data to be retained, all data that is older than this value will be removed by the purge process.
age: 1 seconds
# A boolean switch that can be used to disable the purging of data. This is used if the process should be stopped from running.
enabled: False
# time until next run (assums in seconds)
wait: 5